-- MySQL Script generated by MySQL Workbench
-- Thu Jun 11 06:25:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema taxes_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taxes_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taxes_test` DEFAULT CHARACTER SET utf8 ;
USE `taxes_test` ;

-- -----------------------------------------------------
-- Table `taxes_test`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `password_hash` VARCHAR(125) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taxes_test`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`admin` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `admin_id_UNIQUE` (`account_id` ASC) VISIBLE,
  CONSTRAINT `admin_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `taxes_test`.`account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taxes_test`.`report_general`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`report_general` (
  `report_general_id` INT NOT NULL AUTO_INCREMENT,
  `employees_number` INT NOT NULL,
  PRIMARY KEY (`report_general_id`),
  UNIQUE INDEX `report_general_id_UNIQUE` (`report_general_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taxes_test`.`business_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`business_activity` (
  `business_activity_id` INT NOT NULL AUTO_INCREMENT,
  `report_general_id` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`business_activity_id`),
  UNIQUE INDEX `business_activity_id_UNIQUE` (`business_activity_id` ASC) VISIBLE,
  INDEX `report_general_id_idx` (`report_general_id` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`report_general_id`)
    REFERENCES `taxes_test`.`report_general` (`report_general_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taxes_test`.`first_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`first_group` (
  `first_group_id` INT NOT NULL AUTO_INCREMENT,
  `first_quarter` DOUBLE NOT NULL,
  `second_quarter` DOUBLE NOT NULL,
  `third_quarter` DOUBLE NOT NULL,
  `fourth_quarter` DOUBLE NOT NULL,
  `income` DOUBLE NOT NULL,
  `taxed` DOUBLE NOT NULL,
  PRIMARY KEY (`first_group_id`),
  UNIQUE INDEX `first_group_id_UNIQUE` (`first_group_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taxes_test`.`inspector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`inspector` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(256) NOT NULL,
  `complaint_number` INT NULL DEFAULT '0',
  `reports_in_service` INT NULL DEFAULT '0',
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `inspector_id_UNIQUE` (`account_id` ASC) VISIBLE,
  CONSTRAINT `inspector_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `taxes_test`.`account` (`account_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 106
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taxes_test`.`report_errors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`report_errors` (
  `report_errors_id` INT NOT NULL AUTO_INCREMENT,
  `single_tax` DOUBLE NOT NULL,
  `spec_tax` DOUBLE NOT NULL,
  `fine_percent` INT NOT NULL,
  `penny_sum` DOUBLE NOT NULL,
  PRIMARY KEY (`report_errors_id`),
  UNIQUE INDEX `report_errors_id_UNIQUE` (`report_errors_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taxes_test`.`report_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`report_info` (
  `report_info_id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('SIMPLE', 'SIMPLE_NEW', 'SPECIFYING', 'REFERENCING') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `period` ENUM('I_QUARTER', 'II_QUARTER', 'III_QUARTER', 'IV_QUARTER') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `year` INT NOT NULL,
  `specified_period` ENUM('I_QUARTER', 'II_QUARTER', 'III_QUARTER', 'IV_QUARTER') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `specified_year` INT NOT NULL,
  `authority_name` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`report_info_id`),
  UNIQUE INDEX `report_info_id_UNIQUE` (`report_info_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taxes_test`.`second_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`second_group` (
  `second_group_id` INT NOT NULL AUTO_INCREMENT,
  `first_quarter` DOUBLE NOT NULL,
  `second_quarter` DOUBLE NOT NULL,
  `third_quarter` DOUBLE NOT NULL,
  `fourth_quarter` DOUBLE NOT NULL,
  `income` DOUBLE NOT NULL,
  `taxed` DOUBLE NOT NULL,
  PRIMARY KEY (`second_group_id`),
  UNIQUE INDEX `second_group_id_UNIQUE` (`second_group_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taxes_test`.`third_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`third_group` (
  `third_group_id` INT NOT NULL AUTO_INCREMENT,
  `3_percent` DOUBLE NOT NULL,
  `5_percent` DOUBLE NOT NULL,
  `15_percent` DOUBLE NOT NULL,
  PRIMARY KEY (`third_group_id`),
  UNIQUE INDEX `third_group_id_UNIQUE` (`third_group_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taxes_test`.`report_body`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`report_body` (
  `report_body_id` INT NOT NULL AUTO_INCREMENT,
  `info_id` INT NOT NULL,
  `general_id` INT NOT NULL,
  `first_group_id` INT NULL DEFAULT NULL,
  `second_group_id` INT NULL DEFAULT NULL,
  `third_group_id` INT NULL DEFAULT NULL,
  `error_id` INT NOT NULL,
  PRIMARY KEY (`report_body_id`),
  UNIQUE INDEX `report_body_id_UNIQUE` (`report_body_id` ASC) VISIBLE,
  UNIQUE INDEX `info_id_UNIQUE` (`info_id` ASC) VISIBLE,
  UNIQUE INDEX `general_id_UNIQUE` (`general_id` ASC) VISIBLE,
  UNIQUE INDEX `error_id_UNIQUE` (`error_id` ASC) VISIBLE,
  UNIQUE INDEX `first_group_id_UNIQUE` (`first_group_id` ASC) VISIBLE,
  UNIQUE INDEX `second_goup_id_UNIQUE` (`second_group_id` ASC) VISIBLE,
  UNIQUE INDEX `third_group_id_UNIQUE` (`third_group_id` ASC) VISIBLE,
  CONSTRAINT `error_id`
    FOREIGN KEY (`error_id`)
    REFERENCES `taxes_test`.`report_errors` (`report_errors_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `first_group_id`
    FOREIGN KEY (`first_group_id`)
    REFERENCES `taxes_test`.`first_group` (`first_group_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `general_id`
    FOREIGN KEY (`general_id`)
    REFERENCES `taxes_test`.`report_general` (`report_general_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `info_id`
    FOREIGN KEY (`info_id`)
    REFERENCES `taxes_test`.`report_info` (`report_info_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `second_group_id`
    FOREIGN KEY (`second_group_id`)
    REFERENCES `taxes_test`.`second_group` (`second_group_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `third_group_id`
    FOREIGN KEY (`third_group_id`)
    REFERENCES `taxes_test`.`third_group` (`third_group_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taxes_test`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`user` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(255) NOT NULL,
  `passport` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `tax_group` ENUM('FIRST', 'SECOND', 'THIRD') NOT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`account_id` ASC) VISIBLE,
  CONSTRAINT `user_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `taxes_test`.`account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taxes_test`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taxes_test`.`report` (
  `report_id` INT NOT NULL AUTO_INCREMENT,
  `body_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `inspector_id` INT NOT NULL,
  `date` TIMESTAMP(6) NOT NULL,
  `status` ENUM('PENDING', 'DECLINED', 'ACCEPTED') NOT NULL,
  `review` VARCHAR(500) NULL DEFAULT NULL,
  UNIQUE INDEX `report_id_UNIQUE` (`report_id` ASC) VISIBLE,
  UNIQUE INDEX `body_id_UNIQUE` (`body_id` ASC) VISIBLE,
  INDEX `inspector_id_idx` (`inspector_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `body_id`
    FOREIGN KEY (`body_id`)
    REFERENCES `taxes_test`.`report_body` (`report_body_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `inspector_id`
    FOREIGN KEY (`inspector_id`)
    REFERENCES `taxes_test`.`inspector` (`account_id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `taxes_test`.`user` (`account_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
